# Generated by Django 6.0.5 on 2026-05-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="contect",
            new_name="contact",
        ),
    ]
