# Generated by Django 6.0.5 on 2026-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_experience_project_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("tools", "Creative Tools"),
                ],
                default="frontend",
                max_length=20,
            ),
        ),
    ]
