# Generated by Django 6.0.5 on 2026-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0004_project_image_skill_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="profile/")),
            ],
        ),
    ]
