# Generated by Django 6.0.5 on 2026-05-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Upload your PDF resume here.",
                null=True,
                upload_to="resumes/",
            ),
        ),
    ]
